/**
 * This class is generated by jOOQ
 */
package br.uel.mdd.db;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<br.uel.mdd.db.tables.records.ClassesRecord, java.lang.Integer> IDENTITY_CLASSES = Identities0.IDENTITY_CLASSES;
	public static final org.jooq.Identity<br.uel.mdd.db.tables.records.ExperimentosRecord, java.lang.Long> IDENTITY_EXPERIMENTOS = Identities0.IDENTITY_EXPERIMENTOS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ClassesRecord> CLASSES_PKEY1 = UniqueKeys0.CLASSES_PKEY1;
	public static final org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ExperimentosRecord> EXPERIMENTOS_PKEY = UniqueKeys0.EXPERIMENTOS_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<br.uel.mdd.db.tables.records.ExperimentosRecord, br.uel.mdd.db.tables.records.ClassesRecord> EXPERIMENTOS__EXPERIMENTOS_CLASSE_ID_FKEY = ForeignKeys0.EXPERIMENTOS__EXPERIMENTOS_CLASSE_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<br.uel.mdd.db.tables.records.ClassesRecord, java.lang.Integer> IDENTITY_CLASSES = createIdentity(br.uel.mdd.db.tables.Classes.CLASSES, br.uel.mdd.db.tables.Classes.CLASSES.ID);
		public static org.jooq.Identity<br.uel.mdd.db.tables.records.ExperimentosRecord, java.lang.Long> IDENTITY_EXPERIMENTOS = createIdentity(br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS, br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ClassesRecord> CLASSES_PKEY1 = createUniqueKey(br.uel.mdd.db.tables.Classes.CLASSES, br.uel.mdd.db.tables.Classes.CLASSES.ID);
		public static final org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ExperimentosRecord> EXPERIMENTOS_PKEY = createUniqueKey(br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS, br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<br.uel.mdd.db.tables.records.ExperimentosRecord, br.uel.mdd.db.tables.records.ClassesRecord> EXPERIMENTOS__EXPERIMENTOS_CLASSE_ID_FKEY = createForeignKey(br.uel.mdd.db.Keys.CLASSES_PKEY1, br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS, br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.CLASSE_ID);
	}
}
