/**
 * This class is generated by jOOQ
 */
package br.uel.mdd.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.classes_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> CLASSES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("classes_id_seq", br.uel.mdd.db.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.experimentos_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> EXPERIMENTOS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("experimentos_id_seq", br.uel.mdd.db.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
