/**
 * This class is generated by jOOQ
 */
package br.uel.mdd.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.classes
	 */
	public static final br.uel.mdd.db.tables.Classes CLASSES = br.uel.mdd.db.tables.Classes.CLASSES;

	/**
	 * The table public.experimentos
	 */
	public static final br.uel.mdd.db.tables.Experimentos EXPERIMENTOS = br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS;
}
