/**
 * This class is generated by jOOQ
 */
package br.uel.mdd.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassesRecord extends org.jooq.impl.UpdatableRecordImpl<br.uel.mdd.db.tables.records.ClassesRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -1338354726;

	/**
	 * Setter for <code>public.classes.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.classes.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.classes.nome</code>.
	 */
	public void setNome(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.classes.nome</code>.
	 */
	public java.lang.String getNome() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return br.uel.mdd.db.tables.Classes.CLASSES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return br.uel.mdd.db.tables.Classes.CLASSES.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClassesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClassesRecord value2(java.lang.String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClassesRecord values(java.lang.Integer value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClassesRecord
	 */
	public ClassesRecord() {
		super(br.uel.mdd.db.tables.Classes.CLASSES);
	}

	/**
	 * Create a detached, initialised ClassesRecord
	 */
	public ClassesRecord(java.lang.Integer id, java.lang.String nome) {
		super(br.uel.mdd.db.tables.Classes.CLASSES);

		setValue(0, id);
		setValue(1, nome);
	}
}
