/**
 * This class is generated by jOOQ
 */
package br.uel.mdd.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentosRecord extends org.jooq.impl.UpdatableRecordImpl<br.uel.mdd.db.tables.records.ExperimentosRecord> implements org.jooq.Record6<java.lang.Long, java.lang.Integer, java.lang.Integer[], java.lang.String, java.lang.Integer, byte[]> {

	private static final long serialVersionUID = 15385609;

	/**
	 * Setter for <code>public.experimentos.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.experimentos.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.experimentos.nivel</code>.
	 */
	public void setNivel(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.experimentos.nivel</code>.
	 */
	public java.lang.Integer getNivel() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.experimentos.coeficiente</code>.
	 */
	public void setCoeficiente(java.lang.Integer[] value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.experimentos.coeficiente</code>.
	 */
	public java.lang.Integer[] getCoeficiente() {
		return (java.lang.Integer[]) getValue(2);
	}

	/**
	 * Setter for <code>public.experimentos.nome_imagem</code>.
	 */
	public void setNomeImagem(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.experimentos.nome_imagem</code>.
	 */
	public java.lang.String getNomeImagem() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.experimentos.classe_id</code>.
	 */
	public void setClasseId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.experimentos.classe_id</code>.
	 */
	public java.lang.Integer getClasseId() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.experimentos.imagem</code>.
	 */
	public void setImagem(byte[] value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.experimentos.imagem</code>.
	 */
	public byte[] getImagem() {
		return (byte[]) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Integer, java.lang.Integer[], java.lang.String, java.lang.Integer, byte[]> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Integer, java.lang.Integer[], java.lang.String, java.lang.Integer, byte[]> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.NIVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer[]> field3() {
		return br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.COEFICIENTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.NOME_IMAGEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.CLASSE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field6() {
		return br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS.IMAGEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNivel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer[] value3() {
		return getCoeficiente();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getNomeImagem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getClasseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value6() {
		return getImagem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExperimentosRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExperimentosRecord value2(java.lang.Integer value) {
		setNivel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExperimentosRecord value3(java.lang.Integer[] value) {
		setCoeficiente(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExperimentosRecord value4(java.lang.String value) {
		setNomeImagem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExperimentosRecord value5(java.lang.Integer value) {
		setClasseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExperimentosRecord value6(byte[] value) {
		setImagem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExperimentosRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Integer[] value3, java.lang.String value4, java.lang.Integer value5, byte[] value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExperimentosRecord
	 */
	public ExperimentosRecord() {
		super(br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS);
	}

	/**
	 * Create a detached, initialised ExperimentosRecord
	 */
	public ExperimentosRecord(java.lang.Long id, java.lang.Integer nivel, java.lang.Integer[] coeficiente, java.lang.String nomeImagem, java.lang.Integer classeId, byte[] imagem) {
		super(br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS);

		setValue(0, id);
		setValue(1, nivel);
		setValue(2, coeficiente);
		setValue(3, nomeImagem);
		setValue(4, classeId);
		setValue(5, imagem);
	}
}
