/**
 * This class is generated by jOOQ
 */
package br.uel.mdd.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classes extends org.jooq.impl.TableImpl<br.uel.mdd.db.tables.records.ClassesRecord> {

	private static final long serialVersionUID = -1506352569;

	/**
	 * The singleton instance of <code>public.classes</code>
	 */
	public static final br.uel.mdd.db.tables.Classes CLASSES = new br.uel.mdd.db.tables.Classes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<br.uel.mdd.db.tables.records.ClassesRecord> getRecordType() {
		return br.uel.mdd.db.tables.records.ClassesRecord.class;
	}

	/**
	 * The column <code>public.classes.id</code>.
	 */
	public final org.jooq.TableField<br.uel.mdd.db.tables.records.ClassesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.classes.nome</code>.
	 */
	public final org.jooq.TableField<br.uel.mdd.db.tables.records.ClassesRecord, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>public.classes</code> table reference
	 */
	public Classes() {
		this("classes", null);
	}

	/**
	 * Create an aliased <code>public.classes</code> table reference
	 */
	public Classes(java.lang.String alias) {
		this(alias, br.uel.mdd.db.tables.Classes.CLASSES);
	}

	private Classes(java.lang.String alias, org.jooq.Table<br.uel.mdd.db.tables.records.ClassesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Classes(java.lang.String alias, org.jooq.Table<br.uel.mdd.db.tables.records.ClassesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, br.uel.mdd.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<br.uel.mdd.db.tables.records.ClassesRecord, java.lang.Integer> getIdentity() {
		return br.uel.mdd.db.Keys.IDENTITY_CLASSES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ClassesRecord> getPrimaryKey() {
		return br.uel.mdd.db.Keys.CLASSES_PKEY1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ClassesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ClassesRecord>>asList(br.uel.mdd.db.Keys.CLASSES_PKEY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public br.uel.mdd.db.tables.Classes as(java.lang.String alias) {
		return new br.uel.mdd.db.tables.Classes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public br.uel.mdd.db.tables.Classes rename(java.lang.String name) {
		return new br.uel.mdd.db.tables.Classes(name, null);
	}
}
