/**
 * This class is generated by jOOQ
 */
package br.uel.mdd.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experimentos extends org.jooq.impl.TableImpl<br.uel.mdd.db.tables.records.ExperimentosRecord> {

	private static final long serialVersionUID = -673437809;

	/**
	 * The singleton instance of <code>public.experimentos</code>
	 */
	public static final br.uel.mdd.db.tables.Experimentos EXPERIMENTOS = new br.uel.mdd.db.tables.Experimentos();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<br.uel.mdd.db.tables.records.ExperimentosRecord> getRecordType() {
		return br.uel.mdd.db.tables.records.ExperimentosRecord.class;
	}

	/**
	 * The column <code>public.experimentos.id</code>.
	 */
	public final org.jooq.TableField<br.uel.mdd.db.tables.records.ExperimentosRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.experimentos.nivel</code>.
	 */
	public final org.jooq.TableField<br.uel.mdd.db.tables.records.ExperimentosRecord, java.lang.Integer> NIVEL = createField("nivel", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.experimentos.coeficiente</code>.
	 */
	public final org.jooq.TableField<br.uel.mdd.db.tables.records.ExperimentosRecord, java.lang.Integer[]> COEFICIENTE = createField("coeficiente", org.jooq.impl.SQLDataType.INTEGER.getArrayDataType(), this, "");

	/**
	 * The column <code>public.experimentos.nome_imagem</code>.
	 */
	public final org.jooq.TableField<br.uel.mdd.db.tables.records.ExperimentosRecord, java.lang.String> NOME_IMAGEM = createField("nome_imagem", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.experimentos.classe_id</code>.
	 */
	public final org.jooq.TableField<br.uel.mdd.db.tables.records.ExperimentosRecord, java.lang.Integer> CLASSE_ID = createField("classe_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.experimentos.imagem</code>.
	 */
	public final org.jooq.TableField<br.uel.mdd.db.tables.records.ExperimentosRecord, byte[]> IMAGEM = createField("imagem", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

	/**
	 * Create a <code>public.experimentos</code> table reference
	 */
	public Experimentos() {
		this("experimentos", null);
	}

	/**
	 * Create an aliased <code>public.experimentos</code> table reference
	 */
	public Experimentos(java.lang.String alias) {
		this(alias, br.uel.mdd.db.tables.Experimentos.EXPERIMENTOS);
	}

	private Experimentos(java.lang.String alias, org.jooq.Table<br.uel.mdd.db.tables.records.ExperimentosRecord> aliased) {
		this(alias, aliased, null);
	}

	private Experimentos(java.lang.String alias, org.jooq.Table<br.uel.mdd.db.tables.records.ExperimentosRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, br.uel.mdd.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<br.uel.mdd.db.tables.records.ExperimentosRecord, java.lang.Long> getIdentity() {
		return br.uel.mdd.db.Keys.IDENTITY_EXPERIMENTOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ExperimentosRecord> getPrimaryKey() {
		return br.uel.mdd.db.Keys.EXPERIMENTOS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ExperimentosRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<br.uel.mdd.db.tables.records.ExperimentosRecord>>asList(br.uel.mdd.db.Keys.EXPERIMENTOS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<br.uel.mdd.db.tables.records.ExperimentosRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<br.uel.mdd.db.tables.records.ExperimentosRecord, ?>>asList(br.uel.mdd.db.Keys.EXPERIMENTOS__EXPERIMENTOS_CLASSE_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public br.uel.mdd.db.tables.Experimentos as(java.lang.String alias) {
		return new br.uel.mdd.db.tables.Experimentos(alias, this);
	}

	/**
	 * Rename this table
	 */
	public br.uel.mdd.db.tables.Experimentos rename(java.lang.String name) {
		return new br.uel.mdd.db.tables.Experimentos(name, null);
	}
}
